packages:
  - packages/*

catalog:
  "@effect/language-service": 0.87.3
  "@effect/platform-browser": 4.0.0-rc.117
  "@effect/platform-node": 4.0.0-rc.117
  "@effect/sql-pg": 4.0.0-rc.117
  "@effect/vitest": 4.0.0-rc.117
  "@types/pg": 8.15.5
  alchemy: 2.0.0-beta.78
  better-auth: 1.7.2
  drizzle-orm: 1.0.0-rc.5-ab785fc
  effect: 4.0.0-rc.117
  pg: 8.22.0
  resend: ^6.9.1

catalogMode: manual
