import base from "../../eslint.config.js";
import { defineConfig } from "eslint/config";

export default defineConfig(base, {
  // routeTree.gen.ts is regenerated by TanStack Router on every dev/build run
  ignores: ["src/routeTree.gen.ts", ".tanstack/**", ".nitro/**"],
});
