import { SportTeamSubject } from "@dtpt/core-v2/modules/subjects/variants/sport.schema";

import type { Subject } from "../api.js";

const fallback = "🏈";

const logos = {
  ARI: "🌵",
  ATL: "🔴",
  BAL: "🟣",
  BUF: "❄️",
  CAR: "🔵",
  CHI: "🐻",
  CIN: "🐅",
  CLE: "🟤",
  DAL: "⭐",
  DEN: "⛰️",
  DET: "🦁",
  GB: "🧀",
  HOU: "🚀",
  IND: "🏇",
  JAX: "🐆",
  KC: "🏹",
  LAC: "⚡",
  LAR: "🐏",
  LV: "☠️",
  MIA: "🌊",
  MIN: "🛡️",
  NE: "🇺🇸",
  NO: "⚜️",
  NYG: "🏙️",
  NYJ: "✈️",
  PHI: "🦅",
  PIT: "⚙️",
  SEA: "🌲",
  SF: "🌉",
  TB: "🏴‍☠️",
  TEN: "⚔️",
  WSH: "🏛️",
};

const makeNflTeam = (
  serial: number,
  input: Omit<Parameters<typeof SportTeamSubject.make>[0], "leagueId">,
): Subject => {
  const id: Subject["id"] = `00000000-0000-4000-8000-${String(serial + 200).padStart(12, "0")}`;
  const details = SportTeamSubject.make({ ...input, leagueId: "nfl" });

  return {
    id,
    _tag: details._tag,
    details,
  };
};

export const nflTeams = [
  makeNflTeam(1, {
    location: "Arizona",
    name: "Cardinals",
    display: "Arizona Cardinals",
    abbreviation: "ARI",
    slug: "arizona-cardinals",
  }),
  makeNflTeam(2, {
    location: "Atlanta",
    name: "Falcons",
    display: "Atlanta Falcons",
    abbreviation: "ATL",
    slug: "atlanta-falcons",
  }),
  makeNflTeam(3, {
    location: "Baltimore",
    name: "Ravens",
    display: "Baltimore Ravens",
    abbreviation: "BAL",
    slug: "baltimore-ravens",
  }),
  makeNflTeam(4, {
    location: "Buffalo",
    name: "Bills",
    display: "Buffalo Bills",
    abbreviation: "BUF",
    slug: "buffalo-bills",
  }),
  makeNflTeam(5, {
    location: "Carolina",
    name: "Panthers",
    display: "Carolina Panthers",
    abbreviation: "CAR",
    slug: "carolina-panthers",
  }),
  makeNflTeam(6, {
    location: "Chicago",
    name: "Bears",
    display: "Chicago Bears",
    abbreviation: "CHI",
    slug: "chicago-bears",
  }),
  makeNflTeam(7, {
    location: "Cincinnati",
    name: "Bengals",
    display: "Cincinnati Bengals",
    abbreviation: "CIN",
    slug: "cincinnati-bengals",
  }),
  makeNflTeam(8, {
    location: "Cleveland",
    name: "Browns",
    display: "Cleveland Browns",
    abbreviation: "CLE",
    slug: "cleveland-browns",
  }),
  makeNflTeam(9, {
    location: "Dallas",
    name: "Cowboys",
    display: "Dallas Cowboys",
    abbreviation: "DAL",
    slug: "dallas-cowboys",
  }),
  makeNflTeam(10, {
    location: "Denver",
    name: "Broncos",
    display: "Denver Broncos",
    abbreviation: "DEN",
    slug: "denver-broncos",
  }),
  makeNflTeam(11, {
    location: "Detroit",
    name: "Lions",
    display: "Detroit Lions",
    abbreviation: "DET",
    slug: "detroit-lions",
  }),
  makeNflTeam(12, {
    location: "Green Bay",
    name: "Packers",
    display: "Green Bay Packers",
    abbreviation: "GB",
    slug: "green-bay-packers",
  }),
  makeNflTeam(13, {
    location: "Houston",
    name: "Texans",
    display: "Houston Texans",
    abbreviation: "HOU",
    slug: "houston-texans",
  }),
  makeNflTeam(14, {
    location: "Indianapolis",
    name: "Colts",
    display: "Indianapolis Colts",
    abbreviation: "IND",
    slug: "indianapolis-colts",
  }),
  makeNflTeam(15, {
    location: "Jacksonville",
    name: "Jaguars",
    display: "Jacksonville Jaguars",
    abbreviation: "JAX",
    slug: "jacksonville-jaguars",
  }),
  makeNflTeam(16, {
    location: "Kansas City",
    name: "Chiefs",
    display: "Kansas City Chiefs",
    abbreviation: "KC",
    slug: "kansas-city-chiefs",
  }),
  makeNflTeam(17, {
    location: "Las Vegas",
    name: "Raiders",
    display: "Las Vegas Raiders",
    abbreviation: "LV",
    slug: "las-vegas-raiders",
  }),
  makeNflTeam(18, {
    location: "Los Angeles",
    name: "Chargers",
    display: "Los Angeles Chargers",
    abbreviation: "LAC",
    slug: "los-angeles-chargers",
  }),
  makeNflTeam(19, {
    location: "Los Angeles",
    name: "Rams",
    display: "Los Angeles Rams",
    abbreviation: "LAR",
    slug: "los-angeles-rams",
  }),
  makeNflTeam(20, {
    location: "Miami",
    name: "Dolphins",
    display: "Miami Dolphins",
    abbreviation: "MIA",
    slug: "miami-dolphins",
  }),
  makeNflTeam(21, {
    location: "Minnesota",
    name: "Vikings",
    display: "Minnesota Vikings",
    abbreviation: "MIN",
    slug: "minnesota-vikings",
  }),
  makeNflTeam(22, {
    location: "New England",
    name: "Patriots",
    display: "New England Patriots",
    abbreviation: "NE",
    slug: "new-england-patriots",
  }),
  makeNflTeam(23, {
    location: "New Orleans",
    name: "Saints",
    display: "New Orleans Saints",
    abbreviation: "NO",
    slug: "new-orleans-saints",
  }),
  makeNflTeam(24, {
    location: "New York",
    name: "Giants",
    display: "New York Giants",
    abbreviation: "NYG",
    slug: "new-york-giants",
  }),
  makeNflTeam(25, {
    location: "New York",
    name: "Jets",
    display: "New York Jets",
    abbreviation: "NYJ",
    slug: "new-york-jets",
  }),
  makeNflTeam(26, {
    location: "Philadelphia",
    name: "Eagles",
    display: "Philadelphia Eagles",
    abbreviation: "PHI",
    slug: "philadelphia-eagles",
  }),
  makeNflTeam(27, {
    location: "Pittsburgh",
    name: "Steelers",
    display: "Pittsburgh Steelers",
    abbreviation: "PIT",
    slug: "pittsburgh-steelers",
  }),
  makeNflTeam(28, {
    location: "San Francisco",
    name: "49ers",
    display: "San Francisco 49ers",
    abbreviation: "SF",
    slug: "san-francisco-49ers",
  }),
  makeNflTeam(29, {
    location: "Seattle",
    name: "Seahawks",
    display: "Seattle Seahawks",
    abbreviation: "SEA",
    slug: "seattle-seahawks",
  }),
  makeNflTeam(30, {
    location: "Tampa Bay",
    name: "Buccaneers",
    display: "Tampa Bay Buccaneers",
    abbreviation: "TB",
    slug: "tampa-bay-buccaneers",
  }),
  makeNflTeam(31, {
    location: "Tennessee",
    name: "Titans",
    display: "Tennessee Titans",
    abbreviation: "TEN",
    slug: "tennessee-titans",
  }),
  makeNflTeam(32, {
    location: "Washington",
    name: "Commanders",
    display: "Washington Commanders",
    abbreviation: "WSH",
    slug: "washington-commanders",
  }),
] satisfies readonly Subject[];

export const getNflLogo = (abbr: string) =>
  abbr in logos ? logos[abbr as keyof typeof logos] : fallback;
