import { Subject } from "@dtpt/core-v2/modules/subjects/schema";
import { SportTeamSubject } from "@dtpt/core-v2/modules/subjects/variants/sport.schema";

const fallback = "⚽";

const logos = {
  ALG: "🇩🇿",
  ARG: "🇦🇷",
  AUS: "🇦🇺",
  AUT: "🇦🇹",
  BEL: "🇧🇪",
  BIH: "🇧🇦",
  BRA: "🇧🇷",
  CAN: "🇨🇦",
  CIV: "🇨🇮",
  COL: "🇨🇴",
  CPV: "🇨🇻",
  CRO: "🇭🇷",
  CUW: "🇨🇼",
  CZE: "🇨🇿",
  DRC: "🇨🇩",
  ECU: "🇪🇨",
  EGY: "🇪🇬",
  ENG: "🏴",
  ESP: "🇪🇸",
  FRA: "🇫🇷",
  GER: "🇩🇪",
  GHA: "🇬🇭",
  HAI: "🇭🇹",
  IRN: "🇮🇷",
  IRQ: "🇮🇶",
  JOR: "🇯🇴",
  JPN: "🇯🇵",
  KOR: "🇰🇷",
  KSA: "🇸🇦",
  MAR: "🇲🇦",
  MEX: "🇲🇽",
  NED: "🇳🇱",
  NOR: "🇳🇴",
  NZL: "🇳🇿",
  PAN: "🇵🇦",
  PAR: "🇵🇾",
  POR: "🇵🇹",
  QAT: "🇶🇦",
  RSA: "🇿🇦",
  SCO: "🏴",
  SEN: "🇸🇳",
  SUI: "🇨🇭",
  SWE: "🇸🇪",
  TUN: "🇹🇳",
  TUR: "🇹🇷",
  URU: "🇺🇾",
  USA: "🇺🇸",
  UZB: "🇺🇿",
};

const makeWorldCupTeam = (
  serial: number,
  input: Omit<Parameters<typeof SportTeamSubject.make>[0], "leagueId">,
): Subject => {
  const id = Subject.fields.id.make(
    `00000000-0000-4000-8000-${String(serial + 300).padStart(12, "0")}`,
  );
  const details = SportTeamSubject.make({ ...input, leagueId: "world-cup" });

  return {
    id,
    _tag: details._tag,
    details,
  };
};

const name = "National Team";

export const worldCupTeams = [
  makeWorldCupTeam(1, {
    location: "Mexico",
    name,
    display: "Mexico",
    abbreviation: "MEX",
    slug: "mexico",
  }),
  makeWorldCupTeam(2, {
    location: "South Africa",
    name,
    display: "South Africa",
    abbreviation: "RSA",
    slug: "south-africa",
  }),
  makeWorldCupTeam(3, {
    location: "South Korea",
    name,
    display: "South Korea",
    abbreviation: "KOR",
    slug: "south-korea",
  }),
  makeWorldCupTeam(4, {
    location: "Czechia",
    name,
    display: "Czechia",
    abbreviation: "CZE",
    slug: "czechia",
  }),
  makeWorldCupTeam(5, {
    location: "Canada",
    name,
    display: "Canada",
    abbreviation: "CAN",
    slug: "canada",
  }),
  makeWorldCupTeam(6, {
    location: "Bosnia and Herzegovina",
    name,
    display: "Bosnia and Herzegovina",
    abbreviation: "BIH",
    slug: "bosnia-and-herzegovina",
  }),
  makeWorldCupTeam(7, {
    location: "Qatar",
    name,
    display: "Qatar",
    abbreviation: "QAT",
    slug: "qatar",
  }),
  makeWorldCupTeam(8, {
    location: "Switzerland",
    name,
    display: "Switzerland",
    abbreviation: "SUI",
    slug: "switzerland",
  }),
  makeWorldCupTeam(9, {
    location: "Brazil",
    name,
    display: "Brazil",
    abbreviation: "BRA",
    slug: "brazil",
  }),
  makeWorldCupTeam(10, {
    location: "Morocco",
    name,
    display: "Morocco",
    abbreviation: "MAR",
    slug: "morocco",
  }),
  makeWorldCupTeam(11, {
    location: "Haiti",
    name,
    display: "Haiti",
    abbreviation: "HAI",
    slug: "haiti",
  }),
  makeWorldCupTeam(12, {
    location: "Scotland",
    name,
    display: "Scotland",
    abbreviation: "SCO",
    slug: "scotland",
  }),
  makeWorldCupTeam(13, {
    location: "United States",
    name,
    display: "United States",
    abbreviation: "USA",
    slug: "united-states",
  }),
  makeWorldCupTeam(14, {
    location: "Paraguay",
    name,
    display: "Paraguay",
    abbreviation: "PAR",
    slug: "paraguay",
  }),
  makeWorldCupTeam(15, {
    location: "Australia",
    name,
    display: "Australia",
    abbreviation: "AUS",
    slug: "australia",
  }),
  makeWorldCupTeam(16, {
    location: "Turkiye",
    name,
    display: "Turkiye",
    abbreviation: "TUR",
    slug: "turkiye",
  }),
  makeWorldCupTeam(17, {
    location: "Germany",
    name,
    display: "Germany",
    abbreviation: "GER",
    slug: "germany",
  }),
  makeWorldCupTeam(18, {
    location: "Curacao",
    name,
    display: "Curacao",
    abbreviation: "CUW",
    slug: "curacao",
  }),
  makeWorldCupTeam(19, {
    location: "Ivory Coast",
    name,
    display: "Ivory Coast",
    abbreviation: "CIV",
    slug: "ivory-coast",
  }),
  makeWorldCupTeam(20, {
    location: "Ecuador",
    name,
    display: "Ecuador",
    abbreviation: "ECU",
    slug: "ecuador",
  }),
  makeWorldCupTeam(21, {
    location: "Netherlands",
    name,
    display: "Netherlands",
    abbreviation: "NED",
    slug: "netherlands",
  }),
  makeWorldCupTeam(22, {
    location: "Japan",
    name,
    display: "Japan",
    abbreviation: "JPN",
    slug: "japan",
  }),
  makeWorldCupTeam(23, {
    location: "Sweden",
    name,
    display: "Sweden",
    abbreviation: "SWE",
    slug: "sweden",
  }),
  makeWorldCupTeam(24, {
    location: "Tunisia",
    name,
    display: "Tunisia",
    abbreviation: "TUN",
    slug: "tunisia",
  }),
  makeWorldCupTeam(25, {
    location: "Belgium",
    name,
    display: "Belgium",
    abbreviation: "BEL",
    slug: "belgium",
  }),
  makeWorldCupTeam(26, {
    location: "Egypt",
    name,
    display: "Egypt",
    abbreviation: "EGY",
    slug: "egypt",
  }),
  makeWorldCupTeam(27, {
    location: "Iran",
    name,
    display: "Iran",
    abbreviation: "IRN",
    slug: "iran",
  }),
  makeWorldCupTeam(28, {
    location: "New Zealand",
    name,
    display: "New Zealand",
    abbreviation: "NZL",
    slug: "new-zealand",
  }),
  makeWorldCupTeam(29, {
    location: "Spain",
    name,
    display: "Spain",
    abbreviation: "ESP",
    slug: "spain",
  }),
  makeWorldCupTeam(30, {
    location: "Cape Verde",
    name,
    display: "Cape Verde",
    abbreviation: "CPV",
    slug: "cape-verde",
  }),
  makeWorldCupTeam(31, {
    location: "Saudi Arabia",
    name,
    display: "Saudi Arabia",
    abbreviation: "KSA",
    slug: "saudi-arabia",
  }),
  makeWorldCupTeam(32, {
    location: "Uruguay",
    name,
    display: "Uruguay",
    abbreviation: "URU",
    slug: "uruguay",
  }),
  makeWorldCupTeam(33, {
    location: "France",
    name,
    display: "France",
    abbreviation: "FRA",
    slug: "france",
  }),
  makeWorldCupTeam(34, {
    location: "Senegal",
    name,
    display: "Senegal",
    abbreviation: "SEN",
    slug: "senegal",
  }),
  makeWorldCupTeam(35, {
    location: "Iraq",
    name,
    display: "Iraq",
    abbreviation: "IRQ",
    slug: "iraq",
  }),
  makeWorldCupTeam(36, {
    location: "Norway",
    name,
    display: "Norway",
    abbreviation: "NOR",
    slug: "norway",
  }),
  makeWorldCupTeam(37, {
    location: "Argentina",
    name,
    display: "Argentina",
    abbreviation: "ARG",
    slug: "argentina",
  }),
  makeWorldCupTeam(38, {
    location: "Algeria",
    name,
    display: "Algeria",
    abbreviation: "ALG",
    slug: "algeria",
  }),
  makeWorldCupTeam(39, {
    location: "Austria",
    name,
    display: "Austria",
    abbreviation: "AUT",
    slug: "austria",
  }),
  makeWorldCupTeam(40, {
    location: "Jordan",
    name,
    display: "Jordan",
    abbreviation: "JOR",
    slug: "jordan",
  }),
  makeWorldCupTeam(41, {
    location: "Portugal",
    name,
    display: "Portugal",
    abbreviation: "POR",
    slug: "portugal",
  }),
  makeWorldCupTeam(42, {
    location: "DR Congo",
    name,
    display: "DR Congo",
    abbreviation: "DRC",
    slug: "dr-congo",
  }),
  makeWorldCupTeam(43, {
    location: "Uzbekistan",
    name,
    display: "Uzbekistan",
    abbreviation: "UZB",
    slug: "uzbekistan",
  }),
  makeWorldCupTeam(44, {
    location: "Colombia",
    name,
    display: "Colombia",
    abbreviation: "COL",
    slug: "colombia",
  }),
  makeWorldCupTeam(45, {
    location: "England",
    name,
    display: "England",
    abbreviation: "ENG",
    slug: "england",
  }),
  makeWorldCupTeam(46, {
    location: "Croatia",
    name,
    display: "Croatia",
    abbreviation: "CRO",
    slug: "croatia",
  }),
  makeWorldCupTeam(47, {
    location: "Ghana",
    name,
    display: "Ghana",
    abbreviation: "GHA",
    slug: "ghana",
  }),
  makeWorldCupTeam(48, {
    location: "Panama",
    name,
    display: "Panama",
    abbreviation: "PAN",
    slug: "panama",
  }),
] satisfies readonly Subject[];

export const getWorldCupLogo = (abbr: string) =>
  abbr in logos ? logos[abbr as keyof typeof logos] : fallback;
