const fallback = "🏒";

const logos = new Map(
  Object.entries({
    ANA: "🦆",
    BOS: "🐻",
    BUF: "⚔️",
    CGY: "🔥",
    CAR: "🌀",
    CHI: "🪶",
    COL: "🏔️",
    CBJ: "🧨",
    DAL: "⭐",
    DET: "🔴",
    EDM: "🛢️",
    FLA: "🐆",
    LA: "👑",
    MIN: "🌲",
    MTL: "🇨🇦",
    NSH: "🎸",
    NJ: "😈",
    NYI: "🏝️",
    NYR: "🗽",
    OTT: "🏛️",
    PHI: "🧡",
    PIT: "🐧",
    SJ: "🦈",
    SEA: "🐙",
    STL: "🎺",
    TB: "⚡",
    TOR: "🍁",
    UTAH: "🦣",
    VAN: "🐋",
    VGK: "🛡️",
    WSH: "🦅",
    WPG: "✈️",
  }),
);

export const getNhlLogo = (abbr: string) => logos.get(abbr) ?? fallback;
